development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: test
  user: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: test
  user: root
  password:
  socket: /tmp/mysql.sock